export const LANGUAGES = {
  filipino: {
    code: 'fil',
    label: 'Filipino',
    strings: {
      // Navigation
      tabSearch: 'Maghanap',
      tabMap: 'Botika',
      tabAdherence: 'Gamot Ko',
      tabList: 'Alistahan', // New Cart Tab label
      
      // Search Screen
      searchPlaceholder: 'I-type ang pangalan ng gamot...',
      searchTitle: 'Hanapin ang Katumbas na Gamot',
      scanButton: 'I-scan ang Reseta',
      showPharmacist: 'Ipakita sa Parmaseutiko',
      findPharmacy: 'Hanapin sa Malapit na Botika',
      learnMore: 'Alamin Pa',
      moreDetails: 'Higit pang Detalye',
      hideDetails: 'Itago ang Detalye',
      reportPrice: 'Iulat ang Mali',
      addToList: 'Idagdag sa Listahan', // New Add to Cart button label
      removeFromList: 'Alisin sa Listahan', // New Remove button label
      listEmpty: 'Walang laman ang iyong Alistahan.', // New empty cart state
      
      // Result Card Labels
      labelWhatFor: 'Para saan ito?',
      labelGeneric: 'Katumbas na Gamot',
      labelMaxPrice: 'Pinakamataas na Presyo ng DOH',
      labelPerTablet: 'bawat tableta',
      labelNeedsRx: 'Kailangan ng Reseta',
      labelNoRx: 'Mabibili nang Walang Reseta',
      labelAvailable: 'May Available',
      labelLowStock: 'Mababa na ang Stock',
      labelOutOfStock: 'Wala nang Available',
      labelVerified: 'Opisyal na Kasosyo',
      labelLastUpdated: 'Huling na-update',
      labelSource: 'Pinagmulan ng Impormasyon',
      
      // Warnings
      ntiWarning: 'Babala: Ito ay isang Espesyal na Gamot. Kumonsulta muna sa iyong parmaseutiko o doktor bago palitan ng katumbas na gamot.',
      advisoryBar: 'Palaging kumpirmahin sa iyong parmaseutiko o doktor bago palitan ang iyong gamot.',
      rxGateMessage: 'Mayroon po ba kayong wastong reseta para sa gamot na ito?',
      rxGateConfirm: 'Oo, mayroon akong reseta',
      
      // Pharmacist Screen
      pharmacistTitle: 'Ipakita sa Parmaseutiko',
      pharmacistPhrase: 'Pwede po bang hanapin ang katumbas na gamot na ito? Hindi ko po kaya ang may tatak na bersyon.',
      pharmacistBack: 'Bumalik',
      
      // Map Screen
      mapTitle: 'Malapit na Botika',
      mapDisclaimer: 'Ang availability ay batay sa pinakabagong ulat ng aming mga kasosyong botika. Tawagan muna bago pumunta.',
      mapFilterAll: 'Lahat',
      mapFilterVerified: 'Nakumpirma Lamang',
      partnerFormTitle: 'I-update ang Stock',
      partnerFormSubmit: 'I-save ang Update',
      
      // About Modal
      aboutTitle: 'Tungkol sa GeneRX',
      aboutClose: 'Isara',
      aboutSection1Title: 'Ano ang GeneRX?',
      aboutSection1Body: 'Ang GeneRX ay isang libreng app na tumutulong sa mga pasyente na mahanap ang mas abot-kayang katumbas na gamot para sa mga mahal na may tatak na gamot.',
      aboutSection2Title: 'Saan nanggagaling ang datos?',
      aboutSection2Body: 'Lahat ng impormasyon ay mula sa Philippine FDA Drug Registry at sa Pinakamataas na Presyo ng DOH.',
      aboutSection3Title: 'Ano ang HINDI ginagawa ng GeneRX?',
      aboutSection3Body: 'Hindi nagbibigay ng diagnosis. Hindi nagre-reseta. Hindi kapalit ng iyong doktor o parmaseutiko.',
      aboutSection4Title: 'Pangako namin sa inyo',
      aboutSection4Body: 'Ang lahat ng resulta ay mula sa opisyal na mapagkukunan ng pamahalaan. Palaging kumonsulta sa lisensyadong parmaseutiko bago palitan ang iyong gamot.',
      
      // Footer
      footerSource: 'Ang datos ay mula sa Philippine FDA Drug Registry at DOH.',
      
      // Errors
      ocrNoMatch: 'Hindi namin nakilala ang gamot. Subukan ulit o i-type ang pangalan.',
      noResults: 'Walang nahanap na katumbas na gamot.',
    }
  },

  english: {
    code: 'en',
    label: 'English',
    strings: {
      tabSearch: 'Search',
      tabMap: 'Pharmacy',
      tabAdherence: 'My Medicines',
      tabList: 'My List',
      searchPlaceholder: 'Type the medicine name...',
      searchTitle: 'Find Generic Alternative',
      scanButton: 'Scan Prescription',
      showPharmacist: 'Show Pharmacist',
      findPharmacy: 'Find Nearby Pharmacy',
      learnMore: 'Learn More',
      moreDetails: 'More Details',
      hideDetails: 'Hide Details',
      reportPrice: 'Report Error',
      addToList: 'Add to List',
      removeFromList: 'Remove from List',
      listEmpty: 'Your Prescription List is empty.',
      labelWhatFor: 'What is this for?',
      labelGeneric: 'Generic Alternative',
      labelMaxPrice: 'DOH Maximum Price',
      labelPerTablet: 'per tablet',
      labelNeedsRx: 'Requires Prescription',
      labelNoRx: 'Available Without Prescription',
      labelAvailable: 'In Stock',
      labelLowStock: 'Low Stock',
      labelOutOfStock: 'Out of Stock',
      labelVerified: 'Official Partner',
      labelLastUpdated: 'Last updated',
      labelSource: 'Information Source',
      ntiWarning: 'Warning: This is a Special Medicine. Please consult your pharmacist or doctor before switching to a generic alternative.',
      advisoryBar: 'Always confirm with your pharmacist or doctor before switching your medicine.',
      rxGateMessage: 'Do you have a valid prescription for this medicine?',
      rxGateConfirm: 'Yes, I have a prescription',
      pharmacistTitle: 'Show to Pharmacist',
      pharmacistPhrase: 'Could you please help me find the generic alternative for this medicine? I cannot afford the branded version.',
      pharmacistBack: 'Go Back',
      mapTitle: 'Nearby Pharmacies',
      mapDisclaimer: 'Availability is based on the latest reports from our partner pharmacies. Please call ahead before visiting.',
      mapFilterAll: 'All',
      mapFilterVerified: 'Verified Only',
      partnerFormTitle: 'Update Stock',
      partnerFormSubmit: 'Save Update',
      aboutTitle: 'About GeneRX',
      aboutClose: 'Close',
      aboutSection1Title: 'What is GeneRX?',
      aboutSection1Body: 'GeneRX is a free app that helps patients find affordable generic alternatives to expensive branded medicines.',
      aboutSection2Title: 'Where does the data come from?',
      aboutSection2Body: 'All information is sourced from the Philippine FDA Drug Registry and the DOH Maximum Drug Retail Price list.',
      aboutSection3Title: 'What GeneRX does NOT do',
      aboutSection3Body: 'It does not diagnose. It does not prescribe. It is not a replacement for your doctor or pharmacist.',
      aboutSection4Title: 'Our commitment to you',
      aboutSection4Body: 'All results come from official government sources. Always consult a licensed pharmacist before switching your medicine.',
      footerSource: 'Data sourced from the Philippine FDA Drug Registry and DOH.',
      ocrNoMatch: 'We could not recognize the medicine. Please try again or type the name manually.',
      noResults: 'No generic alternative found.',
    }
  },

  cebuano: {
    code: 'ceb',
    label: 'Cebuano',
    strings: {
      tabSearch: 'Pangita',
      tabMap: 'Botika',
      tabAdherence: 'Akong Tambal',
      tabList: 'Listahan',
      searchPlaceholder: 'I-type ang ngalan sa tambal...',
      searchTitle: 'Pangitaa ang Katumbas nga Tambal',
      scanButton: 'I-scan ang Reseta',
      showPharmacist: 'Ipakita sa Parmaseutiko',
      findPharmacy: 'Pangitaa ang Duol nga Botika',
      learnMore: 'Hibawi Pa',
      moreDetails: 'Dugang nga Detalye',
      hideDetails: 'Itago ang Detalye',
      reportPrice: 'Ireport ang Sayop',
      addToList: 'I-apil sa Listahan',
      removeFromList: 'Kuhaa sa Listahan',
      listEmpty: 'Walay sulod ang imong Listahan sa Tambal.',
      labelWhatFor: 'Para sa unsa kini?',
      labelGeneric: 'Katumbas nga Tambal',
      labelMaxPrice: 'Pinakataas nga Presyo sa DOH',
      labelPerTablet: 'kada tableta',
      labelNeedsRx: 'Kinahanglan og Reseta',
      labelNoRx: 'Mapalit nga Walay Reseta',
      labelAvailable: 'Naa sa Stock',
      labelLowStock: 'Ubos na ang Stock',
      labelOutOfStock: 'Wala nay Available',
      labelVerified: 'Opisyal nga Kauban',
      labelLastUpdated: 'Katapusang gi-update',
      labelSource: 'Tinubdan sa Impormasyon',
      ntiWarning: 'Pasidaan: Espesyal nga Tambal kini. Mangonsulta una sa imong parmaseutiko o doktor sa dili pa palitan og katumbas nga tambal.',
      advisoryBar: 'Kanunay nga kumpirmahon sa imong parmaseutiko o doktor sa dili pa palitan ang imong tambal.',
      rxGateMessage: 'Naa ba kay valid nga reseta para sa tambal nga kini?',
      rxGateConfirm: 'Oo, naa akoy reseta',
      pharmacistTitle: 'Ipakita sa Parmaseutiko',
      pharmacistPhrase: 'Pwede ba nimong pangitaon ang katumbas nga tambal alang niini? Dili ko makaya ang may tatak nga bersyon.',
      pharmacistBack: 'Balik',
      mapTitle: 'Duol nga Botika',
      mapDisclaimer: 'Ang availability gibase sa pinakabag-o nga report sa among mga kauban nga botika. Tawagan una sa dili pa moadto.',
      mapFilterAll: 'Tanan',
      mapFilterVerified: 'Gikumpirma Lamang',
      partnerFormTitle: 'I-update ang Stock',
      partnerFormSubmit: 'I-save ang Update',
      aboutTitle: 'Mahitungod sa GeneRX',
      aboutClose: 'Isira',
      aboutSection1Title: 'Unsa ang GeneRX?',
      aboutSection1Body: 'Ang GeneRX usa ka libre nga app nga nagtabang sa mga pasyente sa pagpangita og mas baratong katumbas nga tambal para sa mga mahal nga tambal nga may tatak.',
      aboutSection2Title: 'Diin gikan ang datos?',
      aboutSection2Body: 'Ang tanan nga impormasyon gikan sa Philippine FDA Drug Registry ug sa DOH Maximum Drug Retail Price list.',
      aboutSection3Title: 'Unsa ang DILI gibuhat sa GeneRX?',
      aboutSection3Body: 'Wala kini naghatag og diagnosis. Wala kini nagpresribe. Dili kini kailis sa imong doktor o parmaseutiko.',
      aboutSection4Title: 'Ang among pangako kaninyo',
      aboutSection4Body: 'Ang tanan nga resulta gikan sa opisyal nga tinubdan sa gobyerno. Kanunay mangonsulta sa lisensyadong parmaseutiko sa dili pa palitan ang imong tambal.',
      footerSource: 'Ang datos gikan sa Philippine FDA Drug Registry ug DOH.',
      ocrNoMatch: 'Wala namo makilala ang tambal. Sulayi pag-usab o i-type ang ngalan.',
      noResults: 'Walay nakitang katumbas nga tambal.',
    }
  }
};

export const DEFAULT_LANGUAGE = 'filipino';